### ISSUE TITLE
Reloader not working in Python 3.10

### ISSUE THREAD

**Issue by johndonor3** [pgjones/hypercorn#108] opened 2023-03-10 16:28 UTC
I recently migrated a Quart webapp to Python 3.10 and now the reloader is not working; I have to restart the dev app every time I change code during development. This may be related to a Quart [issue I reported](https://github.com/pallets/quart/issues/224), or I might be reading too much into it.

**Comment by godjangollc** [comment] 2023-10-23 16:20
Is already fixed in pull request #148 , we must wait until they merge it into the main branch. I tested it on windows and the issue is gone. You can test it and give me feedback in case I need to change anything. I hope it helps.

**Closed** 2023-10-28 19:04 UTC
