### ISSUE TITLE
Can't be installed with poetry 1.4.0

### ISSUE THREAD

**Issue by dimaqq** [pgjones/hypercorn#102] opened 2023-02-28 05:23 UTC
poetry 1.3.2 intsalled hypercorn fine, but poetry 1.4.0 fails: https://github.com/python-poetry/poetry/issues/7572

other libraries are installed correctly, so... could it be that something is broken specifically in hypercorn artefacts?

**Comment by Oblynx** [comment] 2023-02-28 12:54
Same issue with Poetry 1.4.0:

```
  • Installing hypercorn (0.14.3): Failed

  KeyError

  "There is no item named 'Hypercorn-0.14.3.dist-info/WHEEL' in the archive"

  at /usr/local/lib/python3.11/zipfile.py:1473 in getinfo
      1469│     def getinfo(self, name):
      1470│         """Return the instance of ZipInfo given 'name'."""
      1471│         info = self.NameToInfo.get(name)
      1472│         if info is None:
    → 1473│             raise KeyError(
      1474│                 'There is no item named %r in the archive' % name)
      1475│ 
      1476│         return info
      1477│ 
```

**Comment by dacevedo12** [comment] 2023-02-28 13:22
Maybe related https://github.com/montag451/pypi-mirror/issues/21

**Comment by jakubhejhal** [comment] 2023-03-01 11:15
The issue is with "Hypercorn" package name starting with uppercase "H".

https://github.com/python-poetry/poetry/issues/7572

**Comment by pgjones** [comment] 2023-03-01 20:25
It looks like this will be fixed with poetry, but that I should also lowercase `Hypercorn` in the next release.

Thanks for the help figuring this out.

**Comment by XChikuX** [comment] 2023-04-22 21:31
How close are we to the next release, btw? I don't see a roadmap of features.

**Comment by kskalski** [comment] 2023-04-23 15:17
I think the current version of `poetry` includes `installer` version `0.7.0`, which fixes this issue. It works for me at least and https://github.com/python-poetry/poetry/issues/7572 is now closed.

**Comment by XChikuX** [comment] 2023-06-07 02:21
We can close this. Poetry install for hypercorn has been working fine for a while.

**Closed** 2023-08-21 08:00 UTC
